version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - ./project/.env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./certbot/www:/var/www/certbot/:rw
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw

volumes:
  static:
